### ISSUE TITLE
Randomized Vehicle Wheels

### ISSUE THREAD

**Issue by Scotts-Totts** [Sc0ttM/SEM_InteractionMenu#18] opened 2020-10-18 17:58 UTC
This isn't a new problem but there is an issue where vehicles spawned through both LEO and Fire toolbox will spawn with a random wheelset, instead of their default vehicle wheels (ex. sports rims on a Firetruck). I've found it can be simply fixed by adding to the end of `function SpawnVehicle` the following lines:
`SetVehicleModKit(Vehicle, 0)`
`SetVehicleMod(Vehicle, 23, -1, false)`

**Comment by Sc0ttM** [comment] 2020-10-20 20:51
Thanks for the suggestion, we'll look at adding/fixing it in the next update of the resource

**Comment by Sc0ttM** [comment] 2020-11-15 20:05
This issue should be fixed in the latest version **v1.7**, if ya could verify that the issue is fixed

**Comment by Scotts-Totts** [comment] 2020-11-18 03:19
> This issue should be fixed in the latest version **v1.7**, if ya could verify that the issue is fixed

Appears to be fixed to me.

**Comment by Sc0ttM** [comment] 2020-11-19 10:15
Perfect, Thank you for responding!

**Closed as completed by Sc0ttM** 2020-11-19 10:15 UTC
Labels: Bug, Suggestion, Fixed
