### ISSUE TITLE
Parachute Glitch

### ISSUE THREAD

**Issue by Chucky5063** [Sc0ttM/SEM_InteractionMenu#5] opened 2020-05-20 04:53 UTC
I have tested with both a vanilla and custom server (including vanilla version menu). When the Interaction Menu is started you cannot open your parachute without it glitching out. Once the script is stopped then no problems parachute opens with no problems.

Video Evidence:
https://imgur.com/mRywHmd

**Comment by Sc0ttM** [comment] 2020-05-21 22:20
The root cause of the parachutes not being able to be used has been found a fix of this bug will be released with the next update.

**Closed as completed by Sc0ttM** 2020-05-21 22:20 UTC
Labels: Bug, Verified Issue

**Comment by Chucky5063** [comment] 2020-06-04 21:25
Hi, would you be able to tell me where to fix this problem or tell me when the next update is coming out?

Thank you!
